"""Training-only ablation. Explicit train list required by MMCV list replacement.
Validated against resolved A config; optimizer/model/VAL/TEST inherit unchanged.
"""
_base_ = ['./crane_symeood_k1_port_day2night_v1.py']

custom_imports = {'imports': ['mmrotate.datasets.crane_custom_dota',
             'mmrotate.models.detectors.sym_eood_detector',
             'mmrotate.models.dense_heads.sym_eood_head',
             'mmrotate.models.losses.sym_nfl_loss',
             'mmrotate.models.losses.sym_kld_loss',
             'mmrotate.core.bbox.assigners.sym_pola',
             'mmrotate.datasets.pipelines.port_train_augment'],
 'allow_failed_imports': False}

data = {'train': [{'type': 'CraneDataset',
            'data_root': 'crane_project/data/crane_grab_port_day2night_v1/',
            'ann_file': 'train/annfiles/',
            'img_prefix': 'train/images/',
            'pipeline': [{'type': 'LoadImageFromFile'},
                         {'type': 'LoadAnnotations', 'with_bbox': True},
                         {'type': 'RResize', 'img_scale': (1024, 1024)},
                         {'type': 'PortIsotropicShrink',
                          'prob': 0.5,
                          'scale_range': (0.5, 1.0)},
                         {'type': 'RRandomFlip',
                          'flip_ratio': [0.25, 0.25, 0.25],
                          'direction': ['horizontal', 'vertical', 'diagonal'],
                          'version': 'le90'},
                         {'type': 'Normalize',
                          'mean': [123.675, 116.28, 103.53],
                          'std': [58.395, 57.12, 57.375],
                          'to_rgb': True},
                         {'type': 'Pad',
                          'size': (1024, 1024),
                          'pad_val': {'img': (114.0, 114.0, 114.0)}},
                         {'type': 'DefaultFormatBundle'},
                         {'type': 'Collect', 'keys': ['img', 'gt_bboxes', 'gt_labels']}],
            'version': 'le90'},
           {'type': 'CraneDataset',
            'data_root': 'crane_project/data/crane_grab_port_day2night_v1/',
            'ann_file': 'train_sim/annfiles/',
            'img_prefix': 'train_sim/images/',
            'pipeline': [{'type': 'LoadImageFromFile'},
                         {'type': 'LoadAnnotations', 'with_bbox': True},
                         {'type': 'RResize', 'img_scale': (1024, 1024)},
                         {'type': 'PortIsotropicShrink',
                          'prob': 0.5,
                          'scale_range': (0.5, 1.0)},
                         {'type': 'RRandomFlip',
                          'flip_ratio': [0.25, 0.25, 0.25],
                          'direction': ['horizontal', 'vertical', 'diagonal'],
                          'version': 'le90'},
                         {'type': 'Normalize',
                          'mean': [123.675, 116.28, 103.53],
                          'std': [58.395, 57.12, 57.375],
                          'to_rgb': True},
                         {'type': 'Pad',
                          'size': (1024, 1024),
                          'pad_val': {'img': (114.0, 114.0, 114.0)}},
                         {'type': 'DefaultFormatBundle'},
                         {'type': 'Collect', 'keys': ['img', 'gt_bboxes', 'gt_labels']}],
            'version': 'le90'}]}

work_dir = 'work_dirs/crane_symeood_k1_port_day2night_aug_b_v1'
